spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sping_boot
    username: sping_boot
    password: sping_boot
  jpa:
    hibernate:
      ddl-auto: none
server:
  port: 8080



